# docker-compose.yml
# This file defines the services for your Dockerized network documentation application.
# It orchestrates the backend (Python Flask) and frontend (React) services.
# The frontend will now be accessible on port 3005.
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5004:5000"
    volumes:
      - ./backend:/app
      - network_doc_db:/app/instance
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3005:3000" # Changed host port to 3005
    # IMPORTANT: The 'volumes' key and any lines indented below it must be completely REMOVED.
    # Do NOT include a 'volumes:' key here if you don't have active volume mounts for the frontend.
    depends_on:
      - backend
    command: nginx -g "daemon off;"

# Define the named volume for persistent database storage.
volumes:
  network_doc_db:
