# docker-compose.yml
# This file defines the services for your Dockerized network documentation application.
# It orchestrates the backend (Python Flask) and frontend (React) services.
version: "3.8"

services:
  backend:
    build:
      context: . # Build context is the project root
      dockerfile: backend/Dockerfile.backend # Path to the backend Dockerfile
    ports:
      - "5004:5000" # Maps host's 5004 to backend container's 5000
    volumes:
      # Mount the backend source code for development.
      # This will override the files copied during build, which is fine for dev.
      - ./backend:/app/backend
      # Persistent volume for SQLite DB, located within the backend app directory.
      - network_doc_db:/app/backend/instance
    environment:
      FLASK_ENV: development
    # The CMD in Dockerfile.backend will execute start.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3005:80" # Map host's 3005 to frontend container's 80 (where Nginx listens)
    depends_on:
      - backend # Frontend depends on backend to be up for API calls
    # The CMD in Dockerfile.frontend will execute Nginx directly.

# Define the named volume for persistent database storage.
volumes:
  network_doc_db:
