"""Add total_units to Rack model

Revision ID: 60bfe9461d82
Revises: 00472ffbd096
Create Date: 2025-07-04 20:34:12.421885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text as sa_text

# revision identifiers, used by Alembic.
revision = '60bfe9461d82'
down_revision = '00472ffbd096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add rack_id to patch_panels and switches, and total_units to racks
    
    with op.batch_alter_table('patch_panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rack_id', sa.Integer(), nullable=True))
        # Ensure 'fk_patch_panels_rack_id' is within the parentheses and quotes
        batch_op.create_foreign_key('fk_patch_panels_rack_id', 'racks', ['rack_id'], ['id'])

    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rack_id', sa.Integer(), nullable=True))
        # Ensure 'fk_switches_rack_id' is within the parentheses and quotes
        batch_op.create_foreign_key('fk_switches_rack_id', 'racks', ['rack_id'], ['id'])

    with op.batch_alter_table('racks', schema=None) as batch_op:
        # Corrected: Add server_default for existing rows when adding a NOT NULL column
        batch_op.add_column(sa.Column('total_units', sa.Integer(), nullable=False, server_default=sa_text('42')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('total_units')

    with op.batch_alter_table('switches', schema=None) as batch_op:
        # Drop foreign key before dropping column
        batch_op.drop_constraint('fk_switches_rack_id', type_='foreignkey') # Use the name you assigned
        batch_op.drop_column('rack_id')

    with op.batch_alter_table('patch_panels', schema=None) as batch_op:
        # Drop foreign key before dropping column
        batch_op.drop_constraint('fk_patch_panels_rack_id', type_='foreignkey') # Use the name you assigned
        batch_op.drop_column('rack_id')
    
    # ### end Alembic commands ###
