"""Add IP address to PC and initial schema

Revision ID: c1c0cb148673
Revises: 
Create Date: 2025-06-28 03:36:44.348623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c0cb148673'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('patch_panel_id', sa.Integer(), nullable=False),
    sa.Column('patch_panel_port', sa.String(length=50), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('server_port', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patch_panel_id'], ['patch_panels.id'], ),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.drop_table('servers')
    op.drop_table('pcs')
    op.drop_table('patch_panels')
    # ### end Alembic commands ###
