"""Add office field to PC

Revision ID: ef8cc267ff0c
Revises: 67a6584f3f59
Create Date: 2025-06-30 20:30:38.548097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8cc267ff0c'
down_revision = '67a6584f3f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcs', schema=None) as batch_op:
        batch_op.drop_column('office')

    # ### end Alembic commands ###
